name: Build
on:
 push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Build and push frontend
       uses: docker/build-push-action@v4
       with:
         file: frontend/Dockerfile
         push: true
         tags: user/app:latest

      - name: Build and push backend
        uses: docker/build-and-push-action@v3
        with:
          file: backend/Dockerfile
          push: true
          tags: user/app:latest

  deploy:
   runs-on: self-hosted
   needs: build
   steps:
     - name: SSH and Deploy
       uses: appleboy/ssh-action@v0.1.10
       with:
         host: 81.94.158.252
         script: |
           docker-compose up -d
