name: Chess
on: push
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Start
        working-directory: ./frontend
        run: npm run dev
